repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.10
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/biomejs/pre-commit
  rev: v1.9.4
  hooks:
    - id: biome-check
# https://github.com/astral-sh/ty/issues/269
- repo: local
  hooks:
    - id: ty-check
      name: ty-check
      language: python
      entry: uv run ty check
      pass_filenames: false
      args: [--python=.venv/]
      additional_dependencies: [ty]

