site_name: "LynxKite"

theme:
  name: "material"

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: ["./lynxkite-app/src", "./lynxkite-core/src", "./lynxkite-graph-analytics/src", "./lynxkite-lynxscribe/src"]
