[project]
name = "lynxkite-graph-analytics"
version = "0.1.0"
description = "The graph analytics executor and boxes for LynxKite"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fsspec>=2025.3.2",
    "grand-cypher>=0.13.0",
    "lynxkite-core",
    "matplotlib>=3.10.1",
    "networkx[default]>=3.4.2",
    "numba>=0.61.2",
    "numpy>=2.2.6",
    "osmnx>=2.0.2",
    "pandas>=2.2.3",
    "polars>=1.25.2",
    "pyarrow>=19.0.1",
    "pydantic>=2.11.7",
    "torch>=2.7.0",
    "torch-geometric>=2.6.1",
    "torchdiffeq>=0.2.5",
    "tqdm>=4.67.1",
    "umap-learn>=0.5.9.post2",
    "pykeen>=1.11.1"
]
classifiers = ["License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)"]

[project.urls]
Homepage = "https://github.com/lynxkite/lynxkite-2000/"

[project.optional-dependencies]
gpu = [
    "cudf-cu12>=25.6.0",
    "cuml-cu12>=25.2.1",
    "nx-cugraph-cu12>=25.4.0",
    "polars[gpu]>=1.25.2",
    "pylibcugraph-cu12>=25.4.0",
]

[tool.uv.sources]
lynxkite-core = { workspace = true }
pylibcugraph-cu12 = { index = "nvidia" }

[tool.pytest.ini_options]
asyncio_mode = "auto"

[[tool.uv.index]]
name = "nvidia"
url = "https://pypi.nvidia.com"

[tool.deptry.per_rule_ignores]
DEP002 = ["numba", "pyarrow", "nx-cugraph-cu12", "pylibcugraph-cu12"]
DEP003 = ["gradio", "starlette"]

[tool.deptry.package_module_name_map]
grand-cypher = "grandcypher"
lynxkite-core = "lynxkite"
umap-learn = "umap"
cuml-cu12 = "cuml"
cudf-cu12 = "cudf"

[build-system]
requires = ["uv_build>=0.8.0,<0.9.0"]
build-backend = "uv_build"
