[project]
name = "lynxkite-ops"
version = "0.1.0"
description = "A lightweight dependency for authoring LynxKite operations and executors"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]
