[project]
name = "lynxkite"
version = "0.1.0"
description = "The LynxKite application, with web server and UI"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.6",
    "griffe>=1.7.3",
    "joblib>=1.5.1",
    "lynxkite-core",
    "pycrdt-websocket>=0.16",
    "pycrdt>=0.12.26",
    "pydantic>=2.11.7",
    "sse-starlette>=2.2.1",
    "uvicorn>=0.35.0",
]
classifiers = ["License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)"]

[project.urls]
Homepage = "https://github.com/lynxkite/lynxkite-2000/"

[dependency-groups]
dev = [
    "pydantic-to-typescript>=2.0.0",
    "setuptools>=80.9.0",
]

[tool.uv.sources]
lynxkite-core = { workspace = true }

[build-system]
requires = ["setuptools", "wheel", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]

[tool.setuptools.package-data]
"lynxkite_app.web_assets" = ["*"]
"lynxkite_app.web_assets.assets" = ["*"]

[tool.setuptools]
py-modules = ["build_frontend"]
include-package-data = true

[tool.setuptools.cmdclass]
build_py = "build_frontend.build_py"

[project.scripts]
lynxkite = "lynxkite_app.__main__:main"

[tool.deptry.package_module_name_map]
lynxkite-core = "lynxkite"
sse-starlette = "starlette"

[tool.deptry.per_rule_ignores]
DEP002 = ["pycrdt-websocket", "griffe"]
DEP004 = ["setuptools"]
