name: release
on:
  workflow_dispatch:
jobs:
  publish-lynxkite-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Build
        working-directory: lynxkite-app
        run: uv build
      - name: Publish
        working-directory: lynxkite-app
        run: uv publish
  publish-lynxkite-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Build
        working-directory: lynxkite-core
        run: uv build
      - name: Publish
        working-directory: lynxkite-core
        run: uv publish
  publish-lynxkite-graph-analytics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Build
        working-directory: lynxkite-graph-analytics
        run: uv build
      - name: Publish
        working-directory: lynxkite-graph-analytics
        run: uv publish
