name: test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: |
          uv venv
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
          uv sync

      - name: Run pre-commits
        run: |
          pre-commit run --all-files

      - name: Run Python unittests
        run: |
          pytest --asyncio-mode=auto

      - name: Build the documentation
        run: |
          mkdocs build

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install frontend dependencies
        run: |
          cd lynxkite-app/web
          npm i
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          cd lynxkite-app/web
          npm run build
          npm run test

      - uses: actions/upload-artifact@v4
        name: Upload playwright report
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: lynxkite-app/web/playwright-report/
          retention-days: 30
