name: test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install

      # - name: Debug ty issue
      #   run: |
      #     uv pip install ty
      #     uv pip list
      #     uv run python -m ty check

      - name: Install dependencies
        run: |
          uv venv
          . .venv/bin/activate
          uv pip install \
            -e lynxkite-core/[dev] \
            -e lynxkite-app/[dev] \
            -e lynxkite-graph-analytics/[dev] \
            -e lynxkite-pillow-example/

      - name: Run pre-commits
        run: |
          uv pip install pre-commit
          uv run pre-commit run --all-files

      - name: Run Python unittests
        run: |
          uv run pytest --asyncio-mode=auto

      - name: Build the documentation
        run: |
          uv pip install mkdocs-material mkdocstrings[python]
          uv run mkdocs build

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install frontend dependencies
        run: |
          cd lynxkite-app/web
          npm i
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          uv run bash -c 'cd lynxkite-app/web; npm run build; npm run test'

      - uses: actions/upload-artifact@v4
        name: Upload playwright report
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: lynxkite-app/web/playwright-report/
          retention-days: 30
